const express = require("express");
const cors = require("cors");
const { spawn } = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 10000;
const COOKIE_FILE = process.env.YTDLP_COOKIE_FILE || "/etc/secrets/cookies.txt";
const WRITABLE_COOKIE_FILE = "/tmp/radio-shak-youtube-cookies.txt";
const POT_PROVIDER_URL = process.env.YTDLP_POT_PROVIDER_URL || "http://127.0.0.1:4416";
const USER_AGENT = process.env.YTDLP_USER_AGENT || "";
const VERSION = "1.5";

app.use(cors({
  origin: true,
  methods: ["GET", "POST", "OPTIONS"],
  exposedHeaders: ["Content-Disposition", "Content-Type"]
}));
app.use(express.json({ limit: "1mb" }));

function cookieStatus() {
  try {
    if (!fs.existsSync(COOKIE_FILE)) return { configured: false, readable: false };
    fs.accessSync(COOKIE_FILE, fs.constants.R_OK);
    const stat = fs.statSync(COOKIE_FILE);
    return { configured: true, readable: true, bytes: stat.size };
  } catch (e) {
    return { configured: true, readable: false, error: e.message };
  }
}

function prepareCookies() {
  const status = cookieStatus();
  if (!status.readable) return null;

  try {
    let content = fs.readFileSync(COOKIE_FILE, "utf8");

    // Nettoyage robuste : BOM, retours Windows, espaces accidentels.
    content = content
      .replace(/^\uFEFF/, "")
      .replace(/\r\n/g, "\n")
      .replace(/\r/g, "\n");

    const rawLines = content.split("\n");
    const cookieLines = [];

    for (let line of rawLines) {
      if (!line) continue;

      // Trim uniquement à gauche pour retirer les espaces ajoutés par copier-coller.
      line = line.replace(/^\s+/, "");

      // Ignore les commentaires d'origine : on recrée un en-tête Netscape canonique.
      if (line.startsWith("#")) continue;

      // Un cookie Netscape doit avoir exactement 7 champs séparés par tabulations.
      const parts = line.split("\t");
      if (parts.length !== 7) {
        console.warn("Cookie line ignored: invalid field count", parts.length);
        continue;
      }

      // Ne garde que les domaines YouTube/Google utiles à l'authentification.
      const domain = parts[0].trim();
      if (!/(^|\.)youtube\.com$|(^|\.)google\.com$/i.test(domain)) continue;

      parts[0] = domain;
      cookieLines.push(parts.join("\t"));
    }

    if (!cookieLines.length) {
      throw new Error("Aucune ligne de cookie Netscape valide trouvée dans cookies.txt");
    }

    const normalized = [
      "# Netscape HTTP Cookie File",
      "# Generated by Radio Shak Server v1.4",
      "# Do not edit while the service is running.",
      "",
      ...cookieLines,
      ""
    ].join("\n");

    fs.writeFileSync(WRITABLE_COOKIE_FILE, normalized, {
      encoding: "utf8",
      mode: 0o600
    });

    const firstLine = fs.readFileSync(WRITABLE_COOKIE_FILE, "utf8").split("\n")[0];
    if (firstLine !== "# Netscape HTTP Cookie File") {
      throw new Error(`En-tête cookies invalide après normalisation: ${JSON.stringify(firstLine)}`);
    }

    console.log(`Cookies préparés correctement : ${WRITABLE_COOKIE_FILE} (${Buffer.byteLength(normalized)} bytes)`);
    console.log("=== RADIO SHAK COOKIE FIX V1.4 ACTIF ===");
    return WRITABLE_COOKIE_FILE;

  } catch (e) {
    console.error("Erreur préparation cookies:", e.message);
    return null;
  }
}

app.get("/", (req, res) => {
  res.json({
    ok: true,
    service: "Radio Shak MP3 API",
    version: VERSION,
    cookies: cookieStatus(),
    poTokenProvider: POT_PROVIDER_URL
  });
});

app.get("/health", (req, res) => {
  res.json({
    ok: true,
    version: VERSION,
    cookies: cookieStatus(),
    poTokenProvider: POT_PROVIDER_URL
  });
});

function isAllowedYouTubeUrl(value) {
  try {
    const u = new URL(value);
    const host = u.hostname.replace(/^www\./, "").toLowerCase();
    return ["youtube.com", "m.youtube.com", "music.youtube.com", "youtu.be"].includes(host);
  } catch {
    return false;
  }
}

function cleanFilename(name) {
  return (name || "radio-shak")
    .replace(/[<>:"/\\|?*\x00-\x1F]/g, "_")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120) || "radio-shak";
}

app.post("/api/mp3", async (req, res) => {
  const url = String(req.body?.url || "").trim();

  if (!url || !isAllowedYouTubeUrl(url)) {
    return res.status(400).json({ ok: false, error: "Lien YouTube invalide." });
  }

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "radio-shak-"));
  const outputTemplate = path.join(tempDir, "%(title).120B [%(id)s].%(ext)s");
  const activeCookieFile = prepareCookies();

  const cleanupOutputs = () => {
    try {
      for (const f of fs.readdirSync(tempDir)) {
        try { fs.rmSync(path.join(tempDir, f), { recursive: true, force: true }); } catch {}
      }
    } catch {}
  };

  const cleanupAll = () => {
    try { fs.rmSync(tempDir, { recursive: true, force: true }); } catch {}
  };

  function runYtDlp(strategy) {
    return new Promise((resolve) => {
      cleanupOutputs();

      const args = [
        "--no-playlist",
        "--newline",
        "--js-runtimes", "node",
        "--remote-components", "ejs:github",
        "--socket-timeout", "25",
        "--retries", "2",
        "--fragment-retries", "2",
        "-f", "bestaudio/best",
        "-x",
        "--audio-format", "mp3",
        "--audio-quality", "0",
        "--embed-metadata",
        "--restrict-filenames",
        "-o", outputTemplate,
      ];

      if (strategy.client) {
        args.push("--extractor-args", `youtube:player_client=${strategy.client}`);
      }
      if (strategy.po) {
        args.push("--extractor-args", `youtubepot-bgutilhttp:base_url=${POT_PROVIDER_URL}`);
      }
      if (strategy.cookies && activeCookieFile) {
        args.push("--cookies", activeCookieFile);
      }
      if (USER_AGENT) args.push("--user-agent", USER_AGENT);
      args.push(url);

      console.log(`[Radio Shak] Essai ${strategy.name}: client=${strategy.client || "default"}, cookies=${!!(strategy.cookies && activeCookieFile)}, po=${!!strategy.po}`);

      let stderr = "";
      let stdout = "";
      const proc = spawn("yt-dlp", args, {
        cwd: tempDir,
        env: { ...process.env, HOME: "/tmp" }
      });

      proc.stdout.on("data", d => {
        stdout += d.toString();
        if (stdout.length > 30000) stdout = stdout.slice(-30000);
      });
      proc.stderr.on("data", d => {
        stderr += d.toString();
        if (stderr.length > 30000) stderr = stderr.slice(-30000);
      });
      proc.on("error", err => resolve({ ok: false, strategy: strategy.name, detail: err.message }));
      proc.on("close", code => {
        const files = (() => {
          try { return fs.readdirSync(tempDir).filter(f => f.toLowerCase().endsWith(".mp3")); }
          catch { return []; }
        })();
        resolve({
          ok: code === 0 && files.length > 0,
          code,
          files,
          strategy: strategy.name,
          detail: (stderr || stdout || `yt-dlp exit code ${code}`).trim()
        });
      });
    });
  }

  // IMPORTANT : on essaie SANS cookies d'abord.
  // Les cookies exportés du navigateur peuvent être refusés lorsqu'ils sont réutilisés
  // depuis l'IP d'un datacenter comme Render.
  const strategies = [
    { name: "mweb-po-sans-cookies", client: "mweb", po: true, cookies: false },
    { name: "web-safari-sans-cookies", client: "web_safari", po: false, cookies: false },
    { name: "android-vr-sans-cookies", client: "android_vr", po: false, cookies: false },
    { name: "mweb-po-avec-cookies", client: "mweb", po: true, cookies: true },
  ];

  const failures = [];
  try {
    let success = null;
    for (const strategy of strategies) {
      const result = await runYtDlp(strategy);
      if (result.ok) {
        success = result;
        console.log(`[Radio Shak] Succès avec ${result.strategy}`);
        break;
      }
      failures.push(result);
      console.warn(`[Radio Shak] Échec ${result.strategy}: ${result.detail.slice(0, 700)}`);
    }

    if (!success) {
      const combined = failures.map(x => `[${x.strategy}] ${x.detail}`).join("\n\n").slice(-12000);
      cleanupAll();
      return res.status(502).json({
        ok: false,
        error: "YouTube refuse encore la conversion après plusieurs méthodes.",
        detail: combined,
        version: VERSION,
        cookies: cookieStatus(),
        strategies: failures.map(x => x.strategy)
      });
    }

    const mp3Path = path.join(tempDir, success.files[0]);
    const downloadName = cleanFilename(success.files[0].replace(/\.mp3$/i, "")) + ".mp3";
    res.setHeader("Content-Type", "audio/mpeg");
    res.setHeader("Content-Disposition", `attachment; filename*=UTF-8''${encodeURIComponent(downloadName)}`);
    res.setHeader("X-Radio-Shak-Strategy", success.strategy);

    const stream = fs.createReadStream(mp3Path);
    stream.pipe(res);
    stream.on("close", cleanupAll);
    stream.on("error", () => cleanupAll());
    res.on("close", cleanupAll);
  } catch (e) {
    cleanupAll();
    return res.status(500).json({ ok: false, error: "Erreur interne pendant la conversion.", detail: e.message });
  }
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Radio Shak MP3 API v${VERSION} on ${PORT}`);
  console.log("Cookie file:", COOKIE_FILE);
  console.log("Cookie status:", cookieStatus());
  console.log("PO Token provider:", POT_PROVIDER_URL);
  console.log("Mode v1.5: essais sans cookies en priorité.");
});
